name: ps4debug Payload

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          submodules: recursive # Ensure submodules are checked out

      - name: Set execute permissions for scripts
        run: chmod +x build.sh

      - name: Build and package binaries
        run: ./build.sh

      - name: Release for branch main
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ps4debug-1.0${{ github.run_number }} ps4debug.bin --target ${{ github.sha }} -t ps4debug-1.0${{ github.run_number }}
